language: android
android:
  components:
    - platform-tools
    - tools
  licenses:
    - 'android-sdk-license-.+'

before_script:
    - echo yes | android update sdk -u -a -t tools
    - echo yes | android update sdk -u -a -t build-tools-21.1.2
    - echo yes | android update sdk -u -a -t android-21
    - echo yes | android update sdk -u -a -t extra-google-m2repository
    - echo yes | android update sdk -u -a -t extra-android-m2repository
    - echo yes | android update sdk -u -a -t extra-android-support

script: ./gradlew clean build
